# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-21 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartfarm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compost',
            name='compost_total',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vegetable',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
